use_frameworks!

target 'RoomKit_Example' do
  pod 'RoomKit', :path => '../'

  target 'RoomKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
	pod 'SwiftyJSON'
  end
end
